### PR TITLE
Ben's branch

### PR DESCRIPTION
**Pull request by benchanjamin**
fixed CORS bug due to new url + fixed OP color markers not changing colors on their end

### CODE REVIEW

**Review by nicholaspad — APPROVED** [review]
lgtm!

**Comment by benchanjamin** [comment]
Is food4u on automatic deploy on the main branch?

**Comment by nicholaspad** [comment]
@benchanjamin now it is, sorry about that!

**Comment by benchanjamin** [comment]
np, thanks for your help!

**Pull request merged**
